### ISSUE TITLE
can't run examples

### ISSUE THREAD

**Issue by bernardoaraujor** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#344]
`
[bernardo@arch]: ~/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/Chapter1_Introduction>$ 
[bernardo@arch]: ~/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/Chapter1_Introduction>$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.6/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/usr/lib/python3.6/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 445, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/lib/python3.6/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'notebook'

[bernardo@arch]: ~/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/Chapter1_Introduction>$ jupyter notebook
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
`

**Comment by storrgie** [comment]
This is very much a 'dump your problems on the community' type report. Get Juypter Notebook running properly on your system before you go blaming this project.

**Comment by bernardoaraujor** [comment]
I wasn't blaming anyone.. I was just trying to get some help..
But alright, I'll close the issue.
